title: Vanilla OS
author: Vanilla OS Contributors
email: send@mirko.pm

assets: /assets
uploads: /uploads

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://vanillaos.org"
plugins:
  - jekyll-feed
  - jekyll-sitemap
